ALTER TABLE public.order_preferences
  ADD COLUMN IF NOT EXISTS separate_whites     BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS separate_colors     BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS use_softener        BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS use_degreaser       BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS use_bleach          BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS scent               TEXT,
  ADD COLUMN IF NOT EXISTS stain_treatment     BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS stain_count         INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS special_instructions TEXT;

NOTIFY pgrst, 'reload schema';
